// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoxStorm.Api.Data;

#nullable disable

namespace VoxStorm.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324211618_SessionStatsEndpoint")]
    partial class SessionStatsEndpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("VoxStorm.Api.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentIdeaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentIdeaId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SessionId");

                    b.ToTable("Ideas", (string)null);
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CentralTheme")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Idea", b =>
                {
                    b.HasOne("VoxStorm.Api.Models.Idea", "ParentIdea")
                        .WithMany("ChildIdeas")
                        .HasForeignKey("ParentIdeaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VoxStorm.Api.Models.Participant", "Participant")
                        .WithMany("Ideas")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VoxStorm.Api.Models.Session", "Session")
                        .WithMany("Ideas")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentIdea");

                    b.Navigation("Participant");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Participant", b =>
                {
                    b.HasOne("VoxStorm.Api.Models.Session", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Idea", b =>
                {
                    b.Navigation("ChildIdeas");
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Participant", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("VoxStorm.Api.Models.Session", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
